services:
  api:
    image: ghcr.io/lionelzoc/librechat:latest
    platform: linux/amd64
    container_name: LibreChat-API
    restart: always
    ports:
      - '3080:3080'
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      # No MongoDB connection here - it should be in your .env file
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
    depends_on:
      - rag_api
    networks:
      - librechat-network

  client:
    image: nginx:1.25-alpine
    platform: linux/amd64
    container_name: LibreChat-NGINX
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/chat.omniventus.com:/etc/letsencrypt/live/chat.omniventus.com
      - /etc/letsencrypt/archive/chat.omniventus.com:/etc/letsencrypt/archive/chat.omniventus.com
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
    depends_on:
      - api
    networks:
      - librechat-network

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.5
    platform: linux/amd64
    restart: always
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./meili_data:/meili_data
    networks:
      - librechat-network

  vectordb:
    image: ankane/pgvector:latest
    platform: linux/amd64
    container_name: chat-vectordb
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rag_api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    platform: linux/amd64
    container_name: chat-rag-api
    restart: always
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    depends_on:
      - vectordb
    env_file:
      - .env
    networks:
      - librechat-network

volumes:
  pgdata2:
  meili_data:

networks:
  librechat-network:
    driver: bridge
